[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

lib_deps =
    https://github.com/GyverLibs/EEManager.git
    https://github.com/GyverLibs/EncButton.git
    https://github.com/GyverLibs/GyverMAX7219.git
    https://github.com/GyverLibs/VolAnalyzer.git
    fastled/FastLED@3.6.0
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12